name: CDK Deploy SageMaker AI Studio

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {} # allow manual runs

permissions:
  id-token: write 
  contents: read

env:
  AWS_REGION: eu-central-1 
  STACKS: SageMakerStudioPublicStack # only deploy this stack

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CDK CLI
        run: npm install -g aws-cdk@2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::796973481044:role/OidcRoleStack-GitHubActionsRole4F1BBA26-M995LX6t2E16
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Export CDK env
        id: export
        run: |
          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV
          echo "CDK_DEFAULT_ACCOUNT=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "CDK_DEFAULT_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV

      - run: cdk context --clear
      - run: cdk synth "$STACKS"
      - run: cdk diff "$STACKS"

      - name: CDK Deploy (no approval prompts)
        if: github.event_name == 'push'
        run: cdk deploy "$STACKS" --require-approval never